# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: yquaro <yquaro@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/08/03 22:00:08 by yquaro            #+#    #+#              #
#    Updated: 2019/08/03 23:11:49 by yquaro           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

include ../includes/libft.mk
include includes/ft_string.mk

all: print
	@make -C functions/ all

print:
	@echo \*\*\* Compiling ft_string:

clean:
	@make -C functions/ clean

fclean:
	@make -C functions/ fclean
